# Generated by Django 5.2 on 2025-04-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperadorLogico',
            fields=[
                ('id_departamento', models.IntegerField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('operador', models.CharField(max_length=100)),
                ('ventana_cambio', models.CharField(max_length=100)),
                ('dias', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'operador_logico',
            },
        ),
    ]
