from django.db import models

class Historico_Fija(models.Model):
    id_venta = models.AutoField(primary_key=True)
    cedula_asesor = models.CharField(max_length=20, blank=True, null=True)
    nombre_asesor = models.CharField(max_length=100, blank=True, null=True)
    nombres_apellidos_cliente = models.CharField(max_length=100, blank=True, null=True)
    cedula_cliente = models.CharField(max_length=20, blank=True, null=True)
    tipo_cedula = models.CharField(max_length=10, blank=True, null=True)
    fecha_expedicion = models.DateField(blank=True, null=True)
    lugar_expedicion = models.CharField(max_length=100, blank=True, null=True)
    correo_electronico = models.EmailField(blank=True, null=True)
    correspondencia_electronica = models.BooleanField(blank=True, null=True)
    telefono_1 = models.CharField(max_length=20, blank=True, null=True)
    telefono_2 = models.CharField(max_length=20, blank=True, null=True)
    telefono_grabacion_contrato = models.CharField(max_length=20, blank=True, null=True)
    direccion_rr = models.CharField(max_length=100, blank=True, null=True)
    nombre_conjunto = models.CharField(max_length=100, blank=True, null=True)
    barrio = models.CharField(max_length=100, blank=True, null=True)
    ciudad = models.CharField(max_length=100, blank=True, null=True)
    departamento = models.CharField(max_length=100, blank=True, null=True)
    comunidad = models.CharField(max_length=100, blank=True, null=True)
    nodo = models.CharField(max_length=100, blank=True, null=True)
    estrato = models.CharField(max_length=10, blank=True, null=True)
    venta = models.CharField(max_length=100, blank=True, null=True)
    tipo_gestion = models.CharField(max_length=100, blank=True, null=True)
    servicio = models.CharField(max_length=100, blank=True, null=True)
    deco_adicional = models.CharField(max_length=100, blank=True, null=True)
    campana = models.CharField(max_length=100, blank=True, null=True)
    adicionales = models.CharField(max_length=100, blank=True, null=True)
    codigo_tarifa = models.CharField(max_length=100, blank=True, null=True)
    ptar = models.CharField(max_length=100, blank=True, null=True)
    nombre_paquete_adquirido = models.CharField(max_length=100, blank=True, null=True)
    fecha_grabacion_contrato = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    fecha_instalacion = models.DateField(blank=True, null=True)
    franja_instalacion = models.CharField(max_length=50, blank=True, null=True)
    renta_mensual = models.CharField(max_length=100, blank=True, null=True)
    todo_claro = models.CharField(max_length=10, blank=True, null=True)
    persona_recibe_instalacion = models.CharField(max_length=100, blank=True, null=True)
    observacion = models.CharField(max_length=200, blank=True, null=True)
    link = models.ImageField(upload_to='imagenes/', blank=True, null=True)
    link2 = models.ImageField(upload_to='imagenes/', blank=True, null=True)
    link3 = models.ImageField(upload_to='imagenes/', blank=True, null=True)
    link_autorizacion = models.URLField(blank=True, null=True)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    ultima_modificacion = models.DateTimeField(auto_now=True, blank=True, null=True)
    estado = models.CharField(max_length=50, default="Pendiente", blank=True, null=True)
    tipo_solicitud = models.CharField(max_length=100, blank=True, null=True)
    detalles = models.TextField(blank=True, null=True)
    usuario_modificado = models.CharField(max_length=100, default="Sistema", blank=True, null=True)

    def __str__(self):
        return str(self.id_venta)


class Venta_fija(models.Model): 
    id_venta = models.AutoField(primary_key=True)

    cedula_asesor = models.CharField(max_length=20, blank=True, null=True)
    nombre_asesor = models.CharField(max_length=100, blank=True, null=True)
    nombres_apellidos_cliente = models.CharField(max_length=100, blank=True, null=True)
    cedula_cliente = models.CharField(max_length=20, blank=True, null=True)
    tipo_cedula = models.CharField(max_length=10, blank=True, null=True)
    fecha_expedicion = models.DateField(blank=True, null=True)
    lugar_expedicion = models.CharField(max_length=100, blank=True, null=True)
    correo_electronico = models.EmailField(blank=True, null=True)
    correspondencia_electronica = models.BooleanField(blank=True, null=True)
    telefono_1 = models.CharField(max_length=20, blank=True, null=True)
    telefono_2 = models.CharField(max_length=20, blank=True, null=True)
    telefono_grabacion_contrato = models.CharField(max_length=20, blank=True, null=True)
    direccion_rr = models.CharField(max_length=100, blank=True, null=True)
    nombre_conjunto = models.CharField(max_length=100, blank=True, null=True)
    barrio = models.CharField(max_length=100, blank=True, null=True)
    ciudad = models.CharField(max_length=100, blank=True, null=True)
    departamento = models.CharField(max_length=100, blank=True, null=True)
    comunidad = models.CharField(max_length=100, blank=True, null=True)
    nodo = models.CharField(max_length=100, blank=True, null=True)
    estrato = models.CharField(max_length=10, blank=True, null=True)
    venta = models.CharField(max_length=100, blank=True, null=True)
    tipo_gestion = models.CharField(max_length=100, blank=True, null=True)
    servicio = models.CharField(max_length=100, blank=True, null=True)
    deco_adicional = models.CharField(max_length=100, blank=True, null=True)
    campana = models.CharField(max_length=100, blank=True, null=True)
    adicionales = models.CharField(max_length=100, blank=True, null=True)
    codigo_tarifa = models.CharField(max_length=100, blank=True, null=True)
    ptar = models.CharField(max_length=100, blank=True, null=True)
    nombre_paquete_adquirido = models.CharField(max_length=100, blank=True, null=True)
    fecha_grabacion_contrato = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    fecha_instalacion = models.DateField(blank=True, null=True)
    franja_instalacion = models.CharField(max_length=50, blank=True, null=True)
    renta_mensual = models.CharField(max_length=100, blank=True, null=True)
    todo_claro = models.CharField(max_length=10, blank=True, null=True)
    persona_recibe_instalacion = models.CharField(max_length=100, blank=True, null=True)
    observacion = models.CharField(max_length=200, blank=True, null=True)
    link = models.ImageField(upload_to='imagenes/', blank=True, null=True)
    link2 = models.ImageField(upload_to='imagenes/', blank=True, null=True)
    link3 = models.ImageField(upload_to='imagenes/', blank=True, null=True)
    link_autorizacion = models.URLField(blank=True, null=True)
    fecha_registro = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    ultima_modificacion = models.DateTimeField(auto_now=True, blank=True, null=True)
    estado = models.CharField(max_length=50, default="CANTADA", blank=True, null=True)
    tipo_solicitud = models.CharField(max_length=100, blank=True, null=True)
    detalles = models.TextField(blank=True, null=True)
    usuario_modificado = models.CharField(max_length=100, default="Sistema", blank=True, null=True)


    def __str__(self):
        return str(self.id_venta)