# Generated by Django 5.2 on 2025-04-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fija', '0002_remove_venta_fija_id_venta_venta_fija_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historico_fija',
            name='id_venta',
        ),
        migrations.AddField(
            model_name='historico_fija',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
