# Generated by Django 5.2 on 2025-04-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fija', '0003_remove_historico_fija_id_venta_historico_fija_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historico_fija',
            name='id',
        ),
        migrations.RemoveField(
            model_name='venta_fija',
            name='id',
        ),
        migrations.AddField(
            model_name='historico_fija',
            name='id_venta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='venta_fija',
            name='id_venta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
