# Generated by Django 5.2 on 2025-04-30 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fija', '0004_remove_historico_fija_id_remove_venta_fija_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico_fija',
            name='fecha_grabacion_contrato',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='historico_fija',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 30, 2, 8, 24, 682019, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta_fija',
            name='fecha_grabacion_contrato',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
