# Generated by Django 5.2 on 2025-05-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fija', '0005_alter_historico_fija_fecha_grabacion_contrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico_fija',
            name='cuenta',
            field=models.IntegerField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='historico_fija',
            name='orden_trabajo',
            field=models.IntegerField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='venta_fija',
            name='cuenta',
            field=models.IntegerField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='venta_fija',
            name='orden_trabajo',
            field=models.IntegerField(blank=True, max_length=9, null=True),
        ),
    ]
